name: Frontend CI

on: 
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add UbuntuGIS PPA
        run: |
          sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
          sudo apt-get update

      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            ninja-build \
            pkg-config \
            qtbase5-dev \
            qttools5-dev \
            qttools5-dev-tools \
            libqt5svg5-dev \
            libqt5xmlpatterns5-dev \
            qgis \
            libqgis-dev \
            libgtest-dev \
            libgmock-dev \
            libpqxx-dev libpq-dev \
            libgdal-dev \
            libproj-dev \
            rapidjson-dev

      
      - name: Backend build
        working-directory: frontend
        run: |
          cmake -B build -G Ninja -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug
          cmake --build build --target sigm4_backend


      - name: Frontend  Build
        working-directory: frontend
        run: cmake --build build --verbose
      
      - name: Run tests
        working-directory: frontend
        run: |
          cd build
          ctest --output-on-failure --verbose
      
      - name: Test Summary
        if: always()
        working-directory: frontend/build
        run: |
          ctest --output-on-failure || true